name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for reaching out for help. I will try to get to you ASAP. In the meantime, go ahead and check out our other pages and our wiki.'
        pr-message: 'Thank you for your contributions. We will try to check your code ASAP and merge if all looks good.'
